# MVP Module Metadata
module.id=mvp
module.name=MVP Module
module.version=1.0.0-SNAPSHOT
module.author=Amir
module.description=Minimal Viable Product (MVP) module providing essential features for rapid development and deployment of applications. This module includes core functionalities such as user management, authentication, and basic CRUD operations, enabling developers to quickly build and iterate on their applications while maintaining a solid foundation for future enhancements.
module.type=FEATURE
module.required=false
module.dependencies=common,request-response,security
module.package=io.domain.base
module.privileges=MODULE_ADMIN,MODULE_VIEW,MVP_ADMIN
module.auto-configuration=com.cmedhealth.mvp.config.MvpModuleAutoConfiguration

